name: assign-author-to-PR-&-chore/workflowISSUE
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  assignAuthor:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: assignAuthor
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
